Adding SCS
m4ttsch/omscs-notes pull request #25
Opened 2021-01-28 22:27 UTC by MatthewCaseres

The only thing that seems off is that there is no image for SCS, I think I took care of the other stuff?

2021-01-29 02:43 UTC, m4ttsch requested changes

2021-01-29 02:43 UTC, m4ttsch commented on data/courses.json
> +      "icon": "https://assets.omscs.io/courses/cs6200.png",
Ive given you an icon at https://assets.omscs.io/courses/cs6238.png

2021-01-29 02:54 UTC, m4ttsch requested changes

2021-01-29 02:54 UTC, m4ttsch commented on data/sidebars.json
> +        "design-principles"
You'll need to make sure that these values match the *filenames* of the corresponding lectures. You'll either need to drop the 01/02 from the filenames in `notes/secure-computer-systems` or add them in here.

2021-01-29 02:59 UTC, m4ttsch requested changes

2021-01-29 02:59 UTC, m4ttsch commented on data/courses.json
> +      "start": "/secure-computer-systems/getting-started",
01-getting-started

2021-01-29 03:05 UTC, m4ttsch commented
Overall looks pretty good, but I think we may need to drop the numerical prefixes on the filenames for the notes

2021-01-29 11:54 UTC, MatthewCaseres commented
I removed the numerical prefixes but is it impossible to do such a thing? The idea is that it gives the files an ordering.

2021-02-01 04:16 UTC, m4ttsch approved these changes
This looks good to go. I think we are ready to merge this.

2021-02-11 14:46 UTC, merged